version: '3'

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:

  oracle_db:
    image: "gvenzl/oracle-xe"
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=XE
      - ORACLE_PASSWORD=oracle
    volumes:
      - oradata:/oradata
    networks:
      test:
        ipv4_address: 10.1.0.100

  jenkins:
    image: "uttoniwork/front-end-imc"

  back-end-imc:
    image: "docker.io/library/backend-imc:0.0.1-SNAPSHOT"
    ports:
      - "15003:15003"
    restart: "always"
    links:
      - oracle_db
    depends_on:
      - oracle_db
    networks:
      test:
        ipv4_address: 10.1.0.99

volumes:
  oradata: